services:
  # --- REVERSE PROXY ---
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www/api
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  # --- SPA ---
  spa:
    build:
      target: dev
    volumes:
      - ./spa:/app
      - /app/node_modules
    expose:
      - "3000"

  # --- API ---
  api:
    build:
      target: dev
    volumes:
      - ./api:/var/www/api
    environment:
      - APP_ENV=local
    expose:
      - "9000"
