services:
  # --- API ---
  api:
    build:
      target: prod
    environment:
      - APP_ENV=prod
      - SPA_URL=http://localhost

  # --- REVERSE PROXY ---
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  # --- SPA ---
  spa:
    build:
      target: prod
    expose:
      - "80"
